sonar.organization=soltunemontepre
sonar.projectKey=SoltuneMontepre_medilab2

sonar.issue.ignore.multicriteria=pinActions
sonar.issue.ignore.multicriteria.pinActions.ruleKey=githubactions:S7637
sonar.issue.ignore.multicriteria.pinActions.resourceKey=.github/**
