sonar.organization=soltunemontepre
sonar.projectKey=SoltuneMontepre_medilab2

sonar.issue.ignore.multicriteria=pinActions,lockDependencies
sonar.issue.ignore.multicriteria.pinActions.ruleKey=githubactions:S7637
sonar.issue.ignore.multicriteria.pinActions.resourceKey=.github/**
sonar.issue.ignore.multicriteria.lockDependencies.ruleKey=docker:S8544
sonar.issue.ignore.multicriteria.lockDependencies.resourceKey=tools/dockerfiles/**

sonar.python.coverage.reportPaths=src/core/modules/coverage.xml
sonar.coverage.exclusions=**/__manifest__.py,**/tests/**,**/static/**,src/applications/**,src/tests/**
