version: "3"

set: [pipefail]

dotenv: [src/core/.env.local]

vars:
  DOPPLER_PROJECT: medilab
  DOPPLER_CONFIG: dev
  DOPPLER_RUN: doppler run --project {{.DOPPLER_PROJECT}} --config {{.DOPPLER_CONFIG}} --

includes:
  app:
    taskfile: tools/taskfiles/app.taskfile.yml
    dir: .
    flatten: true
  dev:
    taskfile: tools/taskfiles/dev.taskfile.yml
    dir: .
    flatten: true
  tf:
    taskfile: tools/taskfiles/tf.taskfile.yml
    dir: .
    flatten: true
  test:
    taskfile: tools/taskfiles/test.taskfile.yml
    dir: .
    flatten: true

tasks:
  default:
    cmds:
      - task --list
    silent: true

  setup:
    desc: "Set up repository & start the app"
    silent: true
    cmds:
      - task: doppler
      - task: dev:setup
      - task: upgrade
