{
    "name": "Medilab - Analysis",
    "version": "19.0.1.0.0",
    "summary": "Laboratory testing core: test catalog, parameters, samples, results and machines.",
    "category": "Services/Laboratory",
    "author": "Soltune Montepre",
    "license": "LGPL-3",
    "icon": "/analysis/static/src/theme/img/icons/icon-512x512.png",
    "depends": ["base", "web"],
    "data": [
        "security/ir.model.access.csv",
        "data/res_company_data.xml",
        "views/system/favicon_templates.xml",
        "views/system/login_templates.xml",
        "views/system/res_users_views.xml",
        "views/sample_collection/test_parameter_views.xml",
        "views/system/menus.xml",
    ],
    "assets": {
        "web._assets_primary_variables": [
            (
                "before",
                "web/static/src/scss/primary_variables.scss",
                "analysis/static/src/theme/scss/tokens.scss",
            ),
            (
                "before",
                "web/static/src/scss/primary_variables.scss",
                "analysis/static/src/theme/scss/odoo_variables.scss",
            ),
        ],
        "web._assets_frontend_helpers": [
            (
                "prepend",
                "analysis/static/src/theme/scss/frontend_variables.scss",
            ),
        ],
        "web.assets_backend": [
            "analysis/static/lib/iconify/iconify-icon.min.js",
            "analysis/static/src/theme/js/iconify_icons.js",
            "analysis/static/src/theme/js/iconify_setup.js",
            "analysis/static/src/theme/scss/icons.scss",
            "analysis/static/src/theme/scss/base.scss",
            "analysis/static/src/theme/scss/navbar.scss",
            "analysis/static/src/theme/scss/buttons.scss",
            "analysis/static/src/theme/scss/forms.scss",
            "analysis/static/src/theme/scss/lists.scss",
            "analysis/static/src/theme/scss/kanban.scss",
            "analysis/static/src/theme/scss/modals.scss",
            "analysis/static/src/theme/scss/settings.scss",
            "analysis/static/src/theme/scss/discuss.scss",
            "analysis/static/src/theme/scss/calendar.scss",
            "analysis/static/src/theme/scss/preferences.scss",
            "analysis/static/src/theme/js/app_drawer.js",
            "analysis/static/src/theme/js/boolean_button_group_field.js",
            "analysis/static/src/theme/js/list_column_widths.js",
            "analysis/static/src/theme/js/user_menu.js",
            "analysis/static/src/theme/xml/app_drawer.xml",
            "analysis/static/src/theme/xml/boolean_button_group_field.xml",
            "analysis/static/src/theme/xml/form_status_indicator.xml",
            "analysis/static/src/theme/xml/breadcrumbs.xml",
            "analysis/static/src/theme/xml/view_button.xml",
        ],
        "web.assets_frontend": [
            "analysis/static/lib/iconify/iconify-icon.min.js",
            "analysis/static/src/theme/js/iconify_icons.js",
            "analysis/static/src/theme/js/iconify_setup.js",
            "analysis/static/src/theme/scss/icons.scss",
            "analysis/static/src/theme/scss/login.scss",
            "analysis/static/src/theme/xml/user_switch.xml",
        ],
    },
    "application": True,
}
