{
    "name": "Medilab - E-commerce",
    "version": "20.0.1.0.0",
    "summary": "Adds e-commerce features into the exising core laboratory module.",
    "category": "Services/Laboratory",
    "author": "Soltune Montepre",
    "license": "LGPL-3",
    "depends": ["laboratory"],
    "data": [
        "data/res_currency_data.xml",
        "data/ir_sequence_data.xml",
        "data/ir_cron_data.xml",
        "data/scheduled_job_data.xml",
        "data/permission_data.xml",
        "views/system/res_config_settings_views.xml",
        "views/invoicing/invoice_report_templates.xml",
        "views/invoicing/payos_return_templates.xml",
        "views/invoicing/invoice_views.xml",
        "views/invoicing/payment_link_views.xml",
        "views/system/menus.xml",
    ],
    "application": True,
}
