{
    "name": "Medilab Theme",
    "version": "20.0.1.0.0",
    "summary": "The MediLab look for Odoo: colours, navigation, icons, login page and app icons.",
    "category": "Themes/Backend",
    "author": "Soltune Montepre",
    "license": "LGPL-3",
    "icon": "/sol_theme/static/description/icon.svg",
    "depends": ["web"],
    "application": True,
    "data": [
        "views/favicon_templates.xml",
        "views/login_templates.xml",
        "views/res_users_views.xml",
    ],
    "assets": {
        "web._assets_primary_variables": [
            (
                "before",
                "web/static/src/scss/primary_variables.scss",
                "sol_theme/static/src/scss/tokens.scss",
            ),
            (
                "before",
                "web/static/src/scss/primary_variables.scss",
                "sol_theme/static/src/scss/odoo_variables.scss",
            ),
        ],
        "web._assets_frontend_helpers": [
            (
                "prepend",
                "sol_theme/static/src/scss/frontend_variables.scss",
            ),
        ],
        "web.assets_backend": [
            "sol_theme/static/lib/iconify/iconify-icon.min.js",
            "sol_theme/static/src/js/iconify_icons.js",
            "sol_theme/static/src/js/iconify_setup.js",
            "sol_theme/static/src/scss/icons.scss",
            "sol_theme/static/src/scss/base.scss",
            "sol_theme/static/src/scss/navbar.scss",
            "sol_theme/static/src/scss/buttons.scss",
            "sol_theme/static/src/scss/forms.scss",
            "sol_theme/static/src/scss/lists.scss",
            "sol_theme/static/src/scss/kanban.scss",
            "sol_theme/static/src/scss/modals.scss",
            "sol_theme/static/src/scss/settings.scss",
            "sol_theme/static/src/scss/discuss.scss",
            "sol_theme/static/src/scss/calendar.scss",
            "sol_theme/static/src/scss/preferences.scss",
            "sol_theme/static/src/js/app_drawer.js",
            "sol_theme/static/src/js/boolean_button_group_field.js",
            "sol_theme/static/src/js/list_column_widths.js",
            "sol_theme/static/src/js/user_menu.js",
            "sol_theme/static/src/xml/app_drawer.xml",
            "sol_theme/static/src/xml/boolean_button_group_field.xml",
            "sol_theme/static/src/xml/form_status_indicator.xml",
            "sol_theme/static/src/xml/breadcrumbs.xml",
            "sol_theme/static/src/xml/view_button.xml",
        ],
        "web.assets_frontend": [
            "sol_theme/static/lib/iconify/iconify-icon.min.js",
            "sol_theme/static/src/js/iconify_icons.js",
            "sol_theme/static/src/js/iconify_setup.js",
            "sol_theme/static/src/scss/icons.scss",
            "sol_theme/static/src/scss/login.scss",
            "sol_theme/static/src/scss/portal.scss",
            "sol_theme/static/src/xml/user_switch.xml",
        ],
    },
}
