{
    "name": "Medilab - Testing Data",
    "version": "20.0.1.0.0",
    "summary": "Seeds and configure data for demo purposes.",
    "category": "Services/Laboratory",
    "author": "Soltune Montepre",
    "license": "LGPL-3",
    "depends": ["laboratory"],
    "data": [
        "data/measurement_unit_data.xml",
        "data/subcontractor_data.xml",
        "data/catalog_data.xml",
        "data/machine_data.xml",
        "data/base/res_partner.xml",
        "data/base/res_users.xml",
        "data/laboratory/department.xml",
        "data/laboratory/role.xml",
        "data/laboratory/person.xml",
        "data/laboratory/parameter_method.xml",
        "data/laboratory/task.xml",
    ],
    "post_init_hook": "post_init_hook",
    "application": True,
}
