{
    "name": "Medilab - Testing Data",
    "version": "20.0.1.0.0",
    "summary": "Seeds and configure data for demo purposes.",
    "category": "Services/Laboratory",
    "author": "Soltune Montepre",
    "license": "LGPL-3",
    "depends": ["commerce", "laboratory"],
    "data": [
        "data/measurement_unit_data.xml",
        "data/subcontractor_data.xml",
        "data/catalog_data.xml",
        "data/machine_data.xml",
        "data/base/res_partner.xml",
        "data/base/res_users.xml",
        "data/laboratory/department.xml",
        "data/laboratory/role.xml",
        "data/laboratory/person.xml",
        "data/laboratory/parameter_method.xml",
        "data/base/ir_cron.xml",
        "data/laboratory/scheduled_job.xml",
        "data/base/res_partner_bank.xml",
        "data/base/ir_sequence_date_range.xml",
        "data/base/ir_config_parameter.xml",
        "data/commerce/invoice.xml",
        "data/commerce/payment_link.xml",
        "data/commerce/payment_link_transaction.xml",
        "data/commerce/payment.xml",
        "data/commerce/reconciliation_day.xml",
        "data/laboratory/job_item.xml",
        "data/laboratory/job_run.xml",
    ],
    "post_init_hook": "post_init_hook",
    "application": True,
}
