"""Technical names of the database models of the Laboratory module."""

MODEL_ARCHIVE_MIXIN = "medilab.archive.mixin"
MODEL_CHEMICAL = "medilab.chemical"
MODEL_CODE_MIXIN = "medilab.code.mixin"
MODEL_DEPARTMENT = "medilab.department"
MODEL_MACHINE = "medilab.machine"
MODEL_MACHINE_SERVICE = "medilab.machine.service"
MODEL_MEASUREMENT_UNIT = "medilab.measurement.unit"
MODEL_PARAMETER_GROUP = "medilab.parameter.group"
MODEL_PARAMETER_METHOD = "medilab.parameter.method"
MODEL_PARAMETER_METHOD_MACHINE = "medilab.parameter.method.machine"
MODEL_PERMISSION = "medilab.permission"
MODEL_PERMISSION_MIXIN = "medilab.permission.mixin"
MODEL_PERSON = "medilab.person"
MODEL_QUALITY_REGISTRATION = "medilab.quality.registration"
MODEL_REGULATION = "medilab.regulation"
MODEL_REGULATION_LIMIT = "medilab.regulation.limit"
MODEL_ROLE = "medilab.role"
MODEL_SAMPLE_TYPE = "medilab.sample.type"
MODEL_SUBCONTRACTOR = "medilab.subcontractor"
MODEL_TESTING_FIELD = "medilab.testing.field"
MODEL_TESTING_METHOD = "medilab.testing.method"
MODEL_TEST_PARAMETER = "medilab.test.parameter"
MODEL_UNIT_CATEGORY = "medilab.unit.category"
