{
    "name": "Medilab - Laboratory",
    "version": "20.0.1.0.0",
    "summary": "Laboratory testing core: test catalog, parameters, samples, results and machines.",
    "category": "Services/Laboratory",
    "author": "Soltune Montepre",
    "license": "LGPL-3",
    "icon": "/sol_laboratory/static/description/icon.png",
    "depends": ["base", "web", "hr", "portal", "calendar"],
    "data": [
        "security/res_groups_data.xml",
        "security/ir.access.csv",
        "data/res_company_data.xml",
        "data/ir_sequence_data.xml",
        "data/role_data.xml",
        "data/permission_data.xml",
        "data/person_data.xml",
        "views/master_data/chemical_views.xml",
        "views/master_data/machine_views.xml",
        "views/master_data/measurement_unit_views.xml",
        "views/master_data/parameter_group_views.xml",
        "views/master_data/quality_registration_views.xml",
        "views/master_data/regulation_views.xml",
        "views/master_data/sample_type_views.xml",
        "views/master_data/subcontractor_views.xml",
        "views/master_data/test_parameter_views.xml",
        "views/master_data/testing_field_views.xml",
        "views/master_data/testing_method_views.xml",
        "views/master_data/unit_category_views.xml",
        "views/system/department_views.xml",
        "views/system/permission_views.xml",
        "views/system/person_views.xml",
        "views/system/role_views.xml",
        "views/system/menus.xml",
    ],
    "application": True,
}
