{
    "name": "Medilab - Laboratory",
    "version": "20.0.1.0.0",
    "summary": "Laboratory testing core: test catalog, parameters, samples, results and machines.",
    "category": "Services/Laboratory",
    "author": "Soltune Montepre",
    "license": "LGPL-3",
    "icon": "/sol_laboratory/static/src/theme/img/icons/icon-512x512.png",
    "depends": ["base", "web"],
    "data": [
        "security/res_groups_data.xml",
        "security/ir.access.csv",
        "data/res_company_data.xml",
        "data/ir_sequence_data.xml",
        "data/role_data.xml",
        "data/permission_data.xml",
        "data/person_data.xml",
        "data/task_type_data.xml",
        "views/system/favicon_templates.xml",
        "views/system/login_templates.xml",
        "views/system/res_users_views.xml",
        "views/master_data/chemical_views.xml",
        "views/master_data/machine_views.xml",
        "views/master_data/measurement_unit_views.xml",
        "views/master_data/parameter_group_views.xml",
        "views/master_data/quality_registration_views.xml",
        "views/master_data/regulation_views.xml",
        "views/master_data/sample_type_views.xml",
        "views/master_data/subcontractor_views.xml",
        "views/master_data/test_parameter_views.xml",
        "views/master_data/testing_field_views.xml",
        "views/master_data/testing_method_views.xml",
        "views/master_data/unit_category_views.xml",
        "views/system/department_views.xml",
        "views/system/permission_views.xml",
        "views/system/person_views.xml",
        "views/system/role_views.xml",
        "views/tasks/task_type_views.xml",
        "views/tasks/task_reassign_views.xml",
        "views/tasks/task_views.xml",
        "views/system/menus.xml",
    ],
    "assets": {
        "web._assets_primary_variables": [
            (
                "before",
                "web/static/src/scss/primary_variables.scss",
                "sol_laboratory/static/src/theme/scss/tokens.scss",
            ),
            (
                "before",
                "web/static/src/scss/primary_variables.scss",
                "sol_laboratory/static/src/theme/scss/odoo_variables.scss",
            ),
        ],
        "web._assets_frontend_helpers": [
            (
                "prepend",
                "sol_laboratory/static/src/theme/scss/frontend_variables.scss",
            ),
        ],
        "web.assets_backend": [
            "sol_laboratory/static/lib/iconify/iconify-icon.min.js",
            "sol_laboratory/static/src/theme/js/iconify_icons.js",
            "sol_laboratory/static/src/theme/js/iconify_setup.js",
            "sol_laboratory/static/src/theme/scss/icons.scss",
            "sol_laboratory/static/src/theme/scss/base.scss",
            "sol_laboratory/static/src/theme/scss/navbar.scss",
            "sol_laboratory/static/src/theme/scss/buttons.scss",
            "sol_laboratory/static/src/theme/scss/forms.scss",
            "sol_laboratory/static/src/theme/scss/lists.scss",
            "sol_laboratory/static/src/theme/scss/kanban.scss",
            "sol_laboratory/static/src/theme/scss/modals.scss",
            "sol_laboratory/static/src/theme/scss/settings.scss",
            "sol_laboratory/static/src/theme/scss/discuss.scss",
            "sol_laboratory/static/src/theme/scss/calendar.scss",
            "sol_laboratory/static/src/theme/scss/preferences.scss",
            "sol_laboratory/static/src/theme/js/app_drawer.js",
            "sol_laboratory/static/src/theme/js/boolean_button_group_field.js",
            "sol_laboratory/static/src/theme/js/list_column_widths.js",
            "sol_laboratory/static/src/theme/js/user_menu.js",
            "sol_laboratory/static/src/theme/xml/app_drawer.xml",
            "sol_laboratory/static/src/theme/xml/boolean_button_group_field.xml",
            "sol_laboratory/static/src/theme/xml/form_status_indicator.xml",
            "sol_laboratory/static/src/theme/xml/breadcrumbs.xml",
            "sol_laboratory/static/src/theme/xml/view_button.xml",
            "sol_laboratory/static/src/views/control_panel/*",
            "sol_laboratory/static/src/views/timeline/*",
            "sol_laboratory/static/src/tasks/dashboard/*",
        ],
        "web.assets_frontend": [
            "sol_laboratory/static/lib/iconify/iconify-icon.min.js",
            "sol_laboratory/static/src/theme/js/iconify_icons.js",
            "sol_laboratory/static/src/theme/js/iconify_setup.js",
            "sol_laboratory/static/src/theme/scss/icons.scss",
            "sol_laboratory/static/src/theme/scss/login.scss",
            "sol_laboratory/static/src/theme/xml/user_switch.xml",
        ],
    },
    "application": True,
}
