name: cd-core

permissions:
  contents: read

concurrency:
  group: medilab-cd-core
  cancel-in-progress: false

on:
  push:
    branches:
      - main
    paths:
      - "src/core/**"
      - "tools/dockerfiles/**"
      - ".github/workflows/cd.core.yml"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          sparse-checkout: |
            src/core
            tools/dockerfiles

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image tags
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/soltunemontepre/medilab
          tags: |
            type=sha,format=long
            type=raw,value=latest

      - name: Build and push image
        uses: docker/build-push-action@v7
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          file: tools/dockerfiles/prod.dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: false
